name: Test Self-Hosted Runner

on:
  workflow_dispatch:  # manual trigger

jobs:
  build:
    runs-on: saturn
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Run program
        run: ./build/runner_test
