name: CI
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, debian-12]
        compiler: [
          gcc-10, gcc-11, gcc-12, gcc-13, gcc-14, gcc-15,
          clang-14, clang-15, clang-16, clang-17, clang-18, clang-19, clang-20
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run build inside container
        run: |
          podman run --rm --userns=keep-id -v /var/github:/var/github ci-${{ matrix.os }} bash -c "
              echo 'Running inside container: ${{ matrix.os }} + ${{ matrix.compiler }}';
              lsb_release -a;
              # Add compiler detection or build logic here
            "

