name: HelloWorld

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Say hello from Saturn
        run: |
          echo "👋 Hello from $(hostname)"
          uname -a
